import os
import json
from datetime import datetime
from pathlib import Path

# Directory to store evidence files
EVIDENCE_DIR = Path("evidence_logs")
EVIDENCE_DIR.mkdir(exist_ok=True)

def save_evidence(username, target_ip, scan_results, ai_prediction):
    """
    Save scan evidence as a JSON log file with timestamp and metadata.
    For a review or audit past scans purpose.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{username}_{target_ip.replace('.', '-')}_{timestamp}.json"
    filepath = EVIDENCE_DIR / filename

    evidence_data = {
        "Generated By": username,
        "Target IP": target_ip,
        "AI Prediction": ai_prediction,
        "Scan Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Total Ports": len(scan_results),
        "Scan Results": scan_results
    }

    with open(filepath, "w") as f:
        json.dump(evidence_data, f, indent=4)

    print(f"[EVIDENCE] Evidence saved at: {filepath}")
    return filepath


def list_evidence_files():
    """Return a list of all saved evidence logs."""
    return [f for f in os.listdir(EVIDENCE_DIR) if f.endswith(".json")]


def load_evidence(filename):
    """Load and return a specific evidence file."""
    filepath = EVIDENCE_DIR / filename
    if filepath.exists():
        with open(filepath, "r") as f:
            return json.load(f)
    else:
        print(f"[EVIDENCE] File not found: {filename}")
        return None
