import io
import json 
from datetime import datetime
import pandas as pd
import streamlit as st 
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle, Paragraph
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def get_logged_in_username():
    """Retrieve the currently logged-in username from Streamlit session state."""
    if "username" in st.session_state and st.session_state["username"]:
        return st.session_state["username"]
    return "Unknown" 


def generate_json(scan_results, target_ip, ai_prediction="N/A"):
    """
    Generate a JSON export of scan results with complete metadata.
    Returns: JSON string (formatted and ready for download)
    """
    username = get_logged_in_username()
    
    # Build comprehensive JSON structure
    export_data = {
        "scan_metadata": {
            "generated_by": username,
            "target_ip": target_ip,
            "scan_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "ai_risk_prediction": ai_prediction,
            "total_open_ports": len(scan_results),
            "scanner_version": "IoTGuard v1.0.0"
        },
        "risk_summary": {
            "high_risk_ports": sum(1 for r in scan_results if "High" in r.get("Risk Level", "")),
            "medium_risk_ports": sum(1 for r in scan_results if "Medium" in r.get("Risk Level", "")),
            "low_risk_ports": sum(1 for r in scan_results if "Low" in r.get("Risk Level", "")),
            "unknown_risk_ports": sum(1 for r in scan_results if "Unknown" in r.get("Risk Level", ""))
        },
        "scan_results": scan_results
    }
    
    # Convert to formatted JSON string (pretty print with indentation)
    json_string = json.dumps(export_data, indent=2, ensure_ascii=False)
    
    return json_string


def generate_pdf(scan_results, target_ip, ai_prediction="N/A"):
    """
    Generate a professionally formatted IoTGuard Vulnerability Assessment Report.
    Automatically detects the logged-in technician username from session state.
    """
    username = get_logged_in_username()
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # ---------- HEADER ----------
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor("#1b263b"))
    c.drawCentredString(width / 2, height - 60, "IoTGuard Vulnerability Assessment Report")

    c.setFillColor(colors.black)
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 100, f"Generated By: {username}")
    c.drawString(50, height - 120, f"Target IP: {target_ip}")
    c.drawString(50, height - 140, f"Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Optional: logo at top right
    # c.drawImage("iotguard_logo.png", 450, height - 90, width=100, preserveAspectRatio=True, mask='auto')

    # Divider
    c.setStrokeColor(colors.HexColor("#1b263b"))
    c.line(50, height - 150, width - 50, height - 150)

    # ---------- SUMMARY SECTION ----------
    total_ports = len(scan_results)
    high = sum(1 for r in scan_results if "High" in r["Risk Level"])
    medium = sum(1 for r in scan_results if "Medium" in r["Risk Level"])
    low = sum(1 for r in scan_results if "Low" in r["Risk Level"])

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, height - 170, "Scan Summary")
    c.setFont("Helvetica", 11)
    c.drawString(60, height - 190, f"High Risk Ports: {high}")
    c.drawString(230, height - 190, f"Medium Risk Ports: {medium}")
    c.drawString(420, height - 190, f"Low Risk Ports: {low}")

    c.drawString(60, height - 210, f"Total Open Ports: {total_ports}")
    c.drawString(230, height - 210, f"AI Risk Prediction: {ai_prediction.upper()}")

    c.setStrokeColor(colors.grey)
    c.line(50, height - 225, width - 50, height - 225)

    # ---------- TABLE STYLES ----------
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle(
        "cell_style",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=11,
        alignment=0,
        spaceAfter=2,
    )

    header_style = ParagraphStyle(
        "header_style",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.white,
        alignment=1,
    )

    # ---------- TABLE HEADER ----------
    data = [[
        Paragraph("Port", header_style),
        Paragraph("Service", header_style),
        Paragraph("Risk Level", header_style),
        Paragraph("Recommendation", header_style),
        Paragraph("Remarks", header_style),
    ]]

    # ---------- TABLE CONTENT ----------
    for result in scan_results:
        port = str(result.get("Port", ""))
        service = str(result.get("Service", ""))
        risk = str(result.get("Risk Level", ""))
        recommendation = str(result.get("Recommendation", ""))

        if "High" in risk:
            remarks = "Immediate action required."
        elif "Medium" in risk:
            remarks = "Review configuration."
        elif "Low" in risk:
            remarks = "Secure if properly maintained."
        else:
            remarks = "Manual review required."

        data.append([
            Paragraph(port, cell_style),
            Paragraph(service, cell_style),
            Paragraph(risk, cell_style),
            Paragraph(recommendation, cell_style),
            Paragraph(remarks, cell_style),
        ])

    # ---------- TABLE CREATION ----------
    table = Table(
        data,
        colWidths=[50, 90, 80, 200, 100],
        repeatRows=1,
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1b263b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))

    table.wrapOn(c, width, height)
    table_height = len(data) * 18
    table.drawOn(c, 50, height - 260 - table_height)

    y_position = height - 280 - table_height

    # ---------- AI SYSTEM SUMMARY ----------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_position - 10, "AI System Summary:")
    c.setFont("Helvetica", 10)
    summary_text = (
        f"Based on analysis of detected open ports and known IoT vulnerabilities, "
        f"the IoTGuard AI model has classified this device as {ai_prediction}. "
        f"Immediate mitigation is advised for high-risk ports, "
        f"and medium-risk configurations should be reviewed to prevent exploitation."
    )

    max_width = 95
    y = y_position - 30
    for i in range(0, len(summary_text), max_width):
        c.drawString(60, y, summary_text[i:i + max_width])
        y -= 12

    # ---------- TECHNICIAN REMARKS ----------
    y -= 20
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, y, "Technician Remarks:")
    c.drawString(380, y, "Technician Signature:")
    c.setFont("Helvetica", 10)
    c.drawString(50, y - 20, "(To be completed after manual verification.)")

    # ---------- FOOTER ----------
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawRightString(width - 50, 40, "Generated by IoTGuard &copy; 2025 | Omni IoT Security Scanner")
    c.drawString(50, 40, "Page 1 of 1")
    c.setFillColor(colors.black)

    # ---------- SAVE PDF ----------
    c.save()
    buffer.seek(0)
    return buffer.getvalue()


def generate_csv(scan_results):
    """Generate a CSV version of the scan results."""
    df = pd.DataFrame(scan_results)
    return df.to_csv(index=False).encode("utf-8")